name: Create Release on Push to Master

on:
  push:
    branches:
      - master

jobs:
  create_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Needed to get all tags

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0' # Replace with your .NET version

      - name: Get Version
        id: get_version
        run: |
          VERSION=$(dotnet --info | grep Version | awk '{print $2}')
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "::set-output name=version::$VERSION"

      - name: Check if Tag Exists
        id: check_tag
        run: |
          TAG="v${{ env.VERSION }}"
          if git show-ref --quiet "refs/tags/$TAG"; then
            echo "::set-output name=exists::true"
            echo "Tag $TAG already exists."
          else
            echo "::set-output name=exists::false"
            echo "Tag $TAG does not exist."
          fi

      - name: Create Tag
        if: steps.check_tag.outputs.exists == 'false'
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git tag -a v${{ env.VERSION }} -m "Release v${{ env.VERSION }}"
          git push origin --tags

      - name: Build
        run: dotnet build --configuration Release

      - name: Publish
        run: dotnet publish -c Release -o ./publish

      - name: Create Release
        uses: actions/create-release@v1
        with:
          tag_name: v${{ env.VERSION }}
          release_name: Release v${{ env.VERSION }}
          body: |
            ## What's New
            *   See CHANGELOG.md for details
          draft: false
          prerelease: ${{ contains(env.VERSION, '-rc') || contains(github.ref, '-beta') || contains(github.ref, '-alpha') }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
            name: publish
            path: ./publish
